services:
  - type: web
    name: wa-bridge
    env: node
    preInstallCommand: |
      echo "Instalando Chromium en tiempo de ejecución..."
      apt-get update
      apt-get install -y wget unzip
      CHROME_VERSION="130.0.6723.58"
      CHROME_ZIP="https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/${CHROME_VERSION}/chrome-linux.zip"
      mkdir -p /opt/chrome
      wget -q $CHROME_ZIP -O /tmp/chrome.zip
      unzip -q /tmp/chrome.zip -d /opt/
      mv /opt/chrome-linux /opt/chrome
      ln -sf /opt/chrome/chrome /usr/bin/google-chrome
      echo "Chromium instalado en /usr/bin/google-chrome"
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
